const mockCars = [
  {
    id: 1,
    brand: "Toyota",
    model: "Camry",
    year: 2023,
    price: 28500,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    mileage: 12000,
    transmission: "Automatic",
    bodyType: "Sedan",
    image:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    description:
      "The Toyota Camry is a sophisticated and fuel-efficient sedan that offers a comfortable ride with plenty of modern features. This hybrid model provides excellent fuel economy without sacrificing performance.",
    features: [
      "Bluetooth Connectivity",
      "Backup Camera",
      "Lane Departure Warning",
      "Adaptive Cruise Control",
      "Keyless Entry",
      "Heated Seats",
    ],
  },
  {
    id: 2,
    brand: "Honda",
    model: "CR-V",
    year: 2022,
    price: 32000,
    fuelType: "Gasoline",
    seatingCapacity: 5,
    mileage: 18500,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://blogs.gomechanic.com/wp-content/uploads/2020/04/0405_Honda_CRV.jpg",
    description:
      "The Honda CR-V is a versatile and reliable compact SUV that offers ample cargo space and a comfortable interior. With its efficient engine and smooth handling, it's perfect for both city driving and weekend adventures.",
    features: [
      "Apple CarPlay",
      "Android Auto",
      "Sunroof",
      "Leather Seats",
      "Blind Spot Monitoring",
      "Wireless Charging",
    ],
  },
  {
    id: 3,
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    price: 45000,
    fuelType: "Electric",
    seatingCapacity: 5,
    mileage: 8000,
    transmission: "Automatic",
    bodyType: "Sedan",
    image:
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
    description:
      "The Tesla Model 3 is an all-electric sedan that combines cutting-edge technology with impressive performance. With its minimalist interior, long range, and advanced autopilot features, it represents the future of automotive design.",
    features: [
      "Autopilot",
      '15" Touchscreen',
      "Glass Roof",
      "Premium Sound System",
      "Supercharger Access",
      "Over-the-air Updates",
    ],
  },
  {
    id: 4,
    brand: "Ford",
    model: "F-150",
    year: 2022,
    price: 52000,
    fuelType: "Gasoline",
    seatingCapacity: 6,
    mileage: 15000,
    transmission: "Automatic",
    bodyType: "Truck",
    image:
      "https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?auto=format&fit=crop&w=800&q=80",
    description:
      "The Ford F-150 is America's best-selling pickup truck for good reason. It offers exceptional towing capacity, a spacious cabin, and innovative features that make work and play easier. This model comes with the powerful EcoBoost engine.",
    features: [
      "Pro Trailer Backup Assist",
      "360-Degree Camera",
      "Tailgate Step",
      "Onboard Generator",
      "Trailer Sway Control",
      "Sync 4 Infotainment",
    ],
  },
  {
    id: 5,
    brand: "BMW",
    model: "3 Series",
    year: 2023,
    price: 48000,
    fuelType: "Gasoline",
    seatingCapacity: 5,
    mileage: 9500,
    transmission: "Automatic",
    bodyType: "Sedan",
    image:
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    description:
      "The BMW 3 Series continues to set the standard for luxury sport sedans. With its perfect balance of performance, comfort, and technology, it delivers an engaging driving experience wrapped in a sophisticated package.",
    features: [
      "iDrive 7.0",
      "Harman Kardon Audio",
      "Ambient Lighting",
      "Gesture Control",
      "Head-Up Display",
      "Parking Assistant",
    ],
  },
  {
    id: 6,
    brand: "Jeep",
    model: "Wrangler",
    year: 2022,
    price: 42000,
    fuelType: "Gasoline",
    seatingCapacity: 4,
    mileage: 22000,
    transmission: "Manual",
    bodyType: "SUV",
    image:
      "https://images.unsplash.com/photo-1626072778346-0ab6604d39c4?auto=format&fit=crop&w=800&q=80",
    description:
      "The Jeep Wrangler is the ultimate off-road vehicle, built to tackle the toughest terrain while providing open-air freedom. This iconic 4x4 combines rugged capability with modern amenities for both adventure and everyday driving.",
    features: [
      "Removable Top",
      "Four-Wheel Drive",
      "Heavy-Duty Suspension",
      "Rock Rails",
      "Water Fording Capability",
      "Trail Rated Badge",
    ],
  },
  {
    id: 7,
    brand: "Chevrolet",
    model: "Corvette",
    year: 2023,
    price: 68000,
    fuelType: "Gasoline",
    seatingCapacity: 2,
    mileage: 5000,
    transmission: "Automatic",
    bodyType: "Sports Car",
    image:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    description:
      "The Chevrolet Corvette C8 represents a revolution in American sports car design with its mid-engine layout. It delivers supercar performance at a fraction of the price, with stunning looks and a driver-focused cockpit.",
    features: [
      "Mid-Engine Design",
      "Performance Data Recorder",
      "Magnetic Ride Control",
      "Bose 14-Speaker Audio",
      "Front Lift System",
      "Custom Drive Modes",
    ],
  },
  {
    id: 8,
    brand: "Subaru",
    model: "Outback",
    year: 2022,
    price: 36500,
    fuelType: "Gasoline",
    seatingCapacity: 5,
    mileage: 19000,
    transmission: "Automatic",
    bodyType: "Wagon",
    image:
      "https://www.topgear.com/sites/default/files/2023/10/BTVDAY%20TWO0601.jpg?w=1784&h=1004",
    description:
      "The Subaru Outback is the perfect vehicle for outdoor enthusiasts. With standard all-wheel drive, generous ground clearance, and a spacious interior, it's ready for adventure while providing the comfort and safety features families need.",
    features: [
      "Symmetrical All-Wheel Drive",
      "X-Mode with Hill Descent Control",
      "Starlink Safety",
      "Roof Rails with Crossbars",
      "EyeSight Driver Assist",
      "Wilderness Package",
    ],
  },
  {
    id: 9,
    brand: "Audi",
    model: "Q5",
    year: 2023,
    price: 54000,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    mileage: 11000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80",
    description:
      "The Audi Q5 is a luxury compact SUV that blends sophisticated design with advanced technology. This plug-in hybrid model offers the perfect balance of efficiency and performance, with Audi's legendary quattro all-wheel drive system.",
    features: [
      "Virtual Cockpit",
      "Bang & Olufsen Sound",
      "Quattro All-Wheel Drive",
      "MMI Touch Response",
      "Matrix LED Headlights",
      "Adaptive Damping",
    ],
  },
  {
    id: 10,
    brand: "Hyundai",
    model: "Tucson",
    year: 2023,
    price: 31000,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    mileage: 14000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://www.financialexpress.com/wp-content/uploads/2023/11/Hyundai-Tucson-front.jpg",
    description:
      "The Hyundai Tucson Hybrid features a bold, futuristic design and an efficient hybrid powertrain. With its comfortable ride, spacious interior, and comprehensive warranty, it offers exceptional value in the compact SUV segment.",
    features: [
      "Digital Key",
      "Panoramic Sunroof",
      "Remote Smart Parking Assist",
      "Bose Premium Audio",
      "Highway Driving Assist",
      "Wireless Charging",
    ],
  },
  {
    id: 11,
    brand: "Porsche",
    model: "911",
    year: 2022,
    price: 115000,
    fuelType: "Gasoline",
    seatingCapacity: 4,
    mileage: 7500,
    transmission: "Automatic",
    bodyType: "Sports Car",
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    description:
      "The Porsche 911 is an iconic sports car that continues to set the benchmark for performance and driving pleasure. With its distinctive silhouette, rear-engine layout, and precision engineering, it delivers an unmatched driving experience.",
    features: [
      "Sport Chrono Package",
      "Adaptive Sports Seats",
      "Porsche Dynamic Chassis Control",
      "Burmester High-End Audio",
      "Rear-Axle Steering",
      "Launch Control",
    ],
  },
  {
    id: 12,
    brand: "Kia",
    model: "Telluride",
    year: 2023,
    price: 44000,
    fuelType: "Gasoline",
    seatingCapacity: 8,
    mileage: 16000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://www.kia.com/us/content/dam/kia/us/en/vehicles/telluride/2025/gallery/exterior/gallery_telluride_2025_exterior-8.jpg/_jcr_content/renditions/cq5dam.thumbnail.1024.680.png",
    description:
      "The Kia Telluride is a midsize SUV that offers exceptional value with its premium feel and generous standard features. With three rows of seating, powerful V6 engine, and advanced safety technology, it's the perfect family vehicle.",
    features: [
      "Nappa Leather Seats",
      "Harman Kardon Audio",
      "Dual Sunroof",
      "Head-Up Display",
      "Self-Leveling Rear Suspension",
      "Highway Driving Assist",
    ],
  },
  {
    id: 13,
    brand: "Mazda",
    model: "CX-5",
    year: 2022,
    price: 33000,
    fuelType: "Gasoline",
    seatingCapacity: 5,
    mileage: 21000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://images.unsplash.com/photo-1626072778346-0ab6604d39c4?auto=format&fit=crop&w=800&q=80",
    description:
      "The Mazda CX-5 stands out in the crowded compact SUV segment with its upscale design and engaging driving dynamics. With premium materials, refined handling, and efficient powertrains, it offers a near-luxury experience at a mainstream price.",
    features: [
      "G-Vectoring Control Plus",
      "Mazda Radar Cruise Control",
      "Bose 10-Speaker Audio",
      "Ventilated Seats",
      "Active Driving Display",
      "i-Activ AWD",
    ],
  },
  {
    id: 14,
    brand: "Volkswagen",
    model: "ID.4",
    year: 2023,
    price: 41000,
    fuelType: "Electric",
    seatingCapacity: 5,
    mileage: 9000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
    description:
      "The Volkswagen ID.4 is an all-electric SUV that combines zero-emission driving with practical utility. With its spacious interior, smooth ride, and competitive range, it makes the transition to electric driving easy and enjoyable.",
    features: [
      "ID. Light",
      "Massage Seats",
      "Augmented Reality Head-Up Display",
      "Travel Assist",
      "Heat Pump",
      "Fast Charging Capability",
    ],
  },
  {
    id: 15,
    brand: "Lexus",
    model: "RX",
    year: 2022,
    price: 56000,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    mileage: 17000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://di-uploads-pod23.dealerinspire.com/haldemanlexusofprinceton/uploads/2020/07/Lexus-RX-350-atomic-silver-gallery-thumbnail-1204x677-LEX-RXL-MY20-0029_M75.jpg",
    description:
      "The Lexus RX Hybrid combines luxury, efficiency, and reliability in a stylish package. With its comfortable ride, whisper-quiet cabin, and advanced safety features, it provides a serene driving experience with the added benefit of hybrid efficiency.",
    features: [
      "Mark Levinson Audio",
      "Power-Folding Rear Seats",
      "Panoramic View Monitor",
      "Touch-Free Power Liftgate",
      "Climate Concierge",
      "Lexus Safety System+ 2.0",
    ],
  },
  {
    id: 16,
    brand: "Nissan",
    model: "Leaf",
    year: 2023,
    price: 28000,
    fuelType: "Electric",
    seatingCapacity: 5,
    mileage: 12000,
    transmission: "Automatic",
    bodyType: "Hatchback",
    image:
      "https://images.unsplash.com/photo-1593055357429-62eaf3b259cc?auto=format&fit=crop&w=800&q=80",
    description:
      "The Nissan Leaf is a pioneering electric vehicle that makes eco-friendly driving accessible. With its practical range, comfortable interior, and user-friendly technology, it's an excellent choice for environmentally conscious drivers.",
    features: [
      "ProPILOT Assist",
      "e-Pedal",
      "Bose Energy Efficient Audio",
      "Around View Monitor",
      "CHAdeMO Quick Charging",
      "NissanConnect EV App",
    ],
  },
  {
    id: 17,
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2022,
    price: 62000,
    fuelType: "Gasoline",
    seatingCapacity: 5,
    mileage: 14000,
    transmission: "Automatic",
    bodyType: "Sedan",
    image:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    description:
      "The Mercedes-Benz E-Class exemplifies luxury sedan excellence with its sophisticated design, cutting-edge technology, and refined driving experience. This model combines traditional luxury with modern innovations for a truly premium experience.",
    features: [
      "MBUX Infotainment",
      "Burmester 3D Surround Sound",
      "Energizing Comfort Control",
      "Air Body Control Suspension",
      "Active Multicontour Seats",
      "DISTRONIC Active Distance Assist",
    ],
  },
  {
    id: 18,
    brand: "Volvo",
    model: "XC60",
    year: 2023,
    price: 49000,
    fuelType: "Hybrid",
    seatingCapacity: 5,
    mileage: 13000,
    transmission: "Automatic",
    bodyType: "SUV",
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Volvo/XC60/10589/1692870711844/front-left-side-47.jpg",
    description:
      "The Volvo XC60 Recharge is a plug-in hybrid luxury SUV that combines Scandinavian design with advanced safety features and eco-friendly performance. With its elegant interior, responsive handling, and efficient powertrain, it offers a premium driving experience.",
    features: [
      "Bowers & Wilkins Audio",
      "Four-Zone Climate Control",
      "Pilot Assist",
      "Orrefors Crystal Gear Selector",
      "360° Camera",
      "City Safety",
    ],
  },
  {
    id: 19,
    brand: "Dodge",
    model: "Challenger",
    year: 2022,
    price: 39000,
    fuelType: "Gasoline",
    seatingCapacity: 5,
    mileage: 18000,
    transmission: "Manual",
    bodyType: "Coupe",
    image:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    description:
      "The Dodge Challenger combines retro muscle car styling with modern performance and technology. With its powerful engine options, spacious interior, and aggressive stance, it offers an authentic American muscle car experience with everyday usability.",
    features: [
      "Launch Control",
      "Line Lock",
      "Performance Pages",
      "Alpine Audio System",
      "Heated and Ventilated Seats",
      "Uconnect 5 Infotainment",
    ],
  },
  {
    id: 20,
    brand: "GMC",
    model: "Sierra",
    year: 2023,
    price: 58000,
    fuelType: "Diesel",
    seatingCapacity: 6,
    mileage: 11000,
    transmission: "Automatic",
    bodyType: "Truck",
    image:
      "https://www.gmcarabia.com/content/dam/gmc/middleeast/master/en/index/trucks/01-images/2023-light-duty-trucks-3000.jpg?imwidth=1920",
    description:
      "The GMC Sierra is a premium full-size pickup truck that combines capability with luxury. This Denali model features a powerful Duramax diesel engine, innovative MultiPro tailgate, and upscale interior appointments for both work and leisure.",
    features: [
      "MultiPro Tailgate",
      "CarbonPro Bed",
      "ProGrade Trailering System",
      "Head-Up Display",
      "Adaptive Ride Control",
      "Transparent Trailer View",
    ],
  },
];

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
export const fetchCars = async () => {
  await delay(1000);
  return mockCars;
};
